# Makefile for the test suite of the Davi Compiler Collection


# (S)ource, (L)ibraries, (O)bjects, (H)eaders
S = ./src/
L = ./lib/
O = ./obj/
H = ./includes/

# (T)okenizer, (C)ompilation engine, (U)tils, ta(B)le, (W)riter
T = tokenizer/
C = compengine/
U = utils/
B = table/
W = writer/

# (TH) Tested Header, (TS) Tested Source
TH = ./../include/
TS = ./../src/

CH = ./../include/
CS = ./../src/


